config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :homes
  get 'home/index'

  root 'home#index'
=======
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :hotels, :controllers => { registrations: 'registrations' }
  devise_for :installs
  resources :facilities do
    resources :bookings
  end
  resources :photos

  devise_scope :hotel do
    get "show/:id" => "registrations#show", as: :hotel
  end

  get "category", to: "facilities#category"

  post "filter", to: "facilities#filter"

  get "results", to: "facilities#results"

  get "booking/:id" => "facilities#new_booking", as: :new_booking

  get "user_bookings" => "bookings#user_bookings", as: :user_bookings

  get "reserve/:id" => "bookings#reserve", as: :reserve

  root 'facilities#index'

  get 'static/index'

  get 'static/categories'

  get 'static/facility_category_list'

  get 'static/single_facility'

  get 'static/add_facility'

  get 'static/login_page'

  get 'static/register_page'

  get 'static/profile'

  get 'static/contact_us'


>>>>>>> 579008f5a1fa7d91706bb5a73fe21633a4510a94
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facility.rb
class Facility < ApplicationRecord
	belongs_to :hotel
	has_many :photos
	has_many :bookings
	

end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy, :new_booking]

  # GET /facilities
  # GET /facilities.json
  def index
    @swiper = Facility.all
    @facility_layouts = ['U-Shape', 'Classroom', 'Theatre', 'Lawn', 'Board-Room', 'Round-Table', 'Cocktail']
    # Last x facilities to be added
  end


  def filter
    redirect_to :action => "results", :county => params[:county], :range_1 => params[:range_1], :range_2 => params[:range_2], :capacity => params[:capacity], :layout => params[:layout], :area => params[:area]
  end

  def results
    @facility_layouts = ['U-Shape', 'Classroom', 'Theatre', 'Lawn', 'Board-Room', 'Round-Table', 'Cocktail']
    filter_params = params
    range = filter_params[:range_1].to_i..filter_params[:range_2].to_i
    @filtered = []
    @facilities = Facility.all
    @facilities.each do |facility|
        if (facility.hotel.city == filter_params[:county]) || (facility.facility_layouts.include? filter_params[:layout]) || (range.include? facility.price.to_i) || (facility.capacity.split(" ").include? filter_params[:capacity]) || (facility.hotel.area == filter_params[:area])
          @filtered.push(facility)
        end
        @filtered
      end
    render :filter
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
    @facility_layouts = ['U-Shape', 'Classroom', 'Theatre', 'Lawn', 'Board-Room', 'Round-Table', 'Cocktail']
  end

  # GET /facilities/1/edit
  def edit
    if @facility.hotel == current_hotel
      # allow edit
      @facility_layouts = @facility.facility_layouts.split(" ")
      @capacity = @facility.capacity.split(" ")
    else
      redirect_to @facility, notice: 'Sorry, only the owner can edit this facility :('
    end

  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)
    # byebug
    @facility.facility_layouts = facility_params[:facility_layouts].join(" ")
    @facility.capacity = facility_params[:capacity].join(" ")

    respond_to do |format|
      if @facility.save
        format.html { redirect_to new_photo_path(@facility), notice: 'Please add photo to complete.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update

    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    if @facility.hotel == current_hotel
      @facility.destroy
      respond_to do |format|
        format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @facility, notice: 'Sorry, only the owner can delete this facility :('
    end
  end

  def new_booking
    @booking = @facility.bookings.build
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :hotel_id, :price, :internet, :parking, :accomodation, :swimming_pool, :pa_system, :bar, :area, :capacity => [], :facility_layouts => [])
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(facility) do |f| %>
  <% if facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :hotel_id, value: current_hotel.id %>
  </div>

  <div class="field">
    <%= f.text_field :name, placeholder: "Facility Name" %>
  </div>

  <div class="field">
    <%= f.number_field :price, placeholder: "Enter Price" %>
  </div>

  <div class="field">
    <%= f.select :internet, options_for_select(["Wifi Only", "Wifi and Cable", "Cable Only", "No Internet"], :selected) %>
    <%= f.label :internet %>
  </div>
  <div class="field">
    <%= f.check_box :parking %>
    <%= f.label :parking %>
  </div>
  <div class="field">
    <%= f.check_box :accomodation %>
    <%= f.label :accomodation %>
  </div>
  <div class="field">
    <%= f.check_box :swimming_pool %>
    <%= f.label :swimming_pool %>
  </div>
  <div class="field">
    <%= f.check_box :pa_system %>
    <%= f.label :pa_system %>
  </div>
  <div class="field">
    <%= f.check_box :bar %>
  </div>

  <div class="field">
    <% @facility_layouts.each do |facility_layout| %>
      <%= f.check_box :facility_layouts, { multiple: true }, facility_layout, false %>
      <%= f.number_field :capacity, { multiple: true } %>
      <%= f.label facility_layout %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/category.html.erb
<div class="row clearleft-custom">
	<% @orientation.each do |facility| %>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="thumbnail"><a href="/facilities/<%= facility.id %>" class="img-link card-image"><%= image_tag Photo.find(facility.photos.ids.sample).image.url, size: "370x250" %><span class="thumbnail-price"><%= number_to_currency(facility.price, :unit => "Kes") %>/<span class="mon">day</span></span></a>
				<div class="caption">
					<h4><a href="/facilities/<%= facility.id %>"><%= facility.name %> in <%= facility.hotel.name %></a></h4>
					<% i = 0 %>
						<% facility.facility_layouts.split(" ").length.times do |orientation| %>
							<div class="col-md-6" style="font-size: 15px;">
								<span class="icon icon-sm icon-darker hotel-icon-10"></span><%= facility.facility_layouts.split(" ")[i] %> - <%= facility.capacity.split(" ")[i] %>
							</div>
							<% i += 1 %>
						<% end %></br>
					<p><%= facility.description %></p>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>


<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :hotel_id, value: current_hotel.id %>
  </div>

  <div class="field">
    <%= f.text_field :name, placeholder: "Facility Name" %>
  </div>

  <div class="field">
    <%= f.number_field :price, placeholder: "Enter Price" %>
  </div>

  <div class="field">
    <%= f.select :internet, options_for_select(["Wifi Only", "Wifi and Cable", "Cable Only", "No Internet"], :selected) %>
    <%= f.label :internet %>
  </div>
  <div class="field">
    <%= f.check_box :parking %>
    <%= f.label :parking %>
  </div>
  <div class="field">
    <%= f.check_box :accomodation %>
    <%= f.label :accomodation %>
  </div>
  <div class="field">
    <%= f.check_box :swimming_pool %>
    <%= f.label :swimming_pool %>
  </div>
  <div class="field">
    <%= f.check_box :pa_system %>
    <%= f.label :pa_system %>
  </div>
  <div class="field">
    <%= f.check_box :bar %>
  </div>
<!-- Layouts and capacity -->
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/filter.html.erb
<div class="search-form-wrap bg-white container-shadow">
  <h3>Filter results</h3>
  <%= form_tag(controller: "facilities", action: "filter") do %>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-3">
          <label for="">Layout</label>
            <%= select_tag :layout, options_for_select(["Select Layout"].concat(@facility_layouts), :select) %>
        </div>
        <div class="col-sm-3">
          <label>Max Price</label>
          <%= number_field_tag :range_2 %>
        </div>
    <div class="form-group width-2">
        <div class="col-sm-3">
          <label for="select-8">No of People</label>
          <%= number_field_tag :capacity %>
        </div>
        <div class="col-sm-3">
          <label>Min Price</label>
          <%= number_field_tag :range_1 %>
        </div>
      </div>
    </div>
    </div>
    <%= submit_tag("Search") %>

  <% end %>
</div>


<h4><%= @filtered.count %> results matched your search</h4>
<% if @filtered.count > 0 %>
  <div class="row clearleft-custom">
    <% @filtered.each do |facility| %>
      <div class="col-xs-12 col-md-7">
        <div class="thumbnail"><a href="/facilities/<%= facility.id %>" class="img-link card-image"><%= image_tag Photo.find(facility.photos.ids.sample).image.url %><span class="thumbnail-price"><%= number_to_currency(facility.price, :unit => "Kes") %>/<span class="mon">day</span></span></a>
          <div class="caption">
            <h4><a href="/facilities/<%= facility.id %>"><%= facility.name %> in <%= link_to facility.hotel.name, hotel_path(facility.hotel) %></a></h4>
            <% i = 0 %>
              <% facility.facility_layouts.split(" ").length.times do |orientation| %>
                <div class="col-md-6" style="font-size: 15px;">
                  <span class="icon icon-sm icon-darker hotel-icon-10"></span><%= facility.facility_layouts.split(" ")[i] %> - <%= facility.capacity.split(" ")[i] %>
                </div>
                <% i += 1 %>
              <% end %></br>
            <p><%= facility.description %></p>
          </div>
        </div>
      </div>
    <% end %>
    <div class="catalog-sidebar range">
      <!-- Google Maps -->
        <div class="sidebar-module cell-sm-3 cell-md-12 cell-md-push-2">
        <style>
           #map {
            height: 400px;
            width: 100%;
           }
        </style>
        <h3>My Google Maps Demo</h3>
        <div id="map"></div>
        <script>

          function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 13,
              center: {lat: -1.2857613, lng: 36.817449}
            });

            // Create an array of alphabetical characters used to label the markers.
            var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

            // Add some markers to the map.
            // Note: The code uses the JavaScript Array.prototype.map() method to
            // create an array of markers based on a given "locations" array.
            // The map() method here has nothing to do with the Google Maps API.
            var markers = locations.map(function(location, i) {
              return new google.maps.Marker({
                position: location,
                label: labels[i % labels.length]
              });
            });

            // Add a marker clusterer to manage the markers.
            var markerCluster = new MarkerClusterer(map, markers,
                {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
          }
          var locations = []
          <% @filtered.each do |facility| %>
            locations.push({lat: <%= facility.hotel.latitude %>, lng: <%= facility.hotel.longitude %>})
          <% end %>
        </script>
        <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
           </script>
           <script async defer
           src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsDME8YAmMgpXL0kjY7ssv3wSi1vzNNFo&callback=initMap">
           </script>


        </div>
    </div>
  </div>

<% else %>
  <p>Sorry no results found</p>
<% end %>

app/views/facilities/index.html.erb
<section>
  <!--Swiper-->
  <div data-height="" data-min-height="600px" class="swiper-container swiper-slider">
    <div class="swiper-wrapper">
      <% @swiper.each do |facility| %>
          <div data-slide-bg="http://wamiori.com/meet/images/slide-2.jpg" class="swiper-slide">
            <div class="swiper-slide-caption">
              <div class="container">
                <p data-caption-animate="fadeInDown" class="h1"><%= facility.hotel.name %> - <%=   facility.name  %></p>
                <p data-caption-animate="fadeInUp" data-caption-delay="400" class="h5" style="padding-right: 500px;"><%= facility.description %></p>
                <div data-caption-animate="fadeInUp" data-caption-delay="400" class="price"><%= number_to_currency(facility.price, :unit => "Kes") %><span>/day</span></div>
                <a href="property-catalog-single.html" data-caption-animate="fadeInUp" data-caption-delay="400" class="btn btn-sm btn-transparent">book now</a> </div>
            </div>
          </div>
      <% end %>

    </div>
    <!-- Swiper Pagination-->
    <div class="swiper-pagination"></div>
  </div>
</section>
<!-- Section Search -->
<section class="section-sm section-sm-mod-1 bg-dark">
  <div class="container position-margin-top undefined">
    <div class="search-form-wrap bg-white container-shadow">
      <h3>Search Conference Facilities</h3>
      <%= form_tag(controller: "facilities", action: "filter") do %>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-4">
              <label for="">County</label>
              <%= text_field_tag :county, @params %>
            </div>
            <div class="col-sm-4">
              <label for="">Area</label>
                <%= text_field_tag :area %>
            </div>
            <div class="col-sm-4">
              <label>Max Price</label>
              <%= number_field_tag :range_2 %>
            </div>
          </div>
        </div>
        <div class="form-group width-2">
          <div class="row">
            <div class="col-sm-4">
              <label for="">Hotel</label>
              <%= select_tag :hotel, options_for_select(["Select Hotel"].push(Hotel.distinct.pluck(:name))) %>
            </div>
            <div class="col-sm-4">
              <label for="">Layout</label>
                <%= select_tag :layout, options_for_select(["Select Layout"].concat(@facility_layouts), :select) %>
            </div>
            <div class="col-sm-4">
              <label>Min Price</label>
              <%= number_field_tag :range_1 %>
            </div>
          </div>
        </div>
        <%= submit_tag("Search") %>

      <% end %>
    </div>
  </div>
</section>
<!--Section Categories-->

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/new_booking.html.erb
<div style="padding-left: 30px;">
  <h1>Book This Facility</h1>

  <%= form_for(@booking, url: facility_bookings_path(@facility) ) do |f| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this facility from being saved:</h2>

        <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :guests %>
      <%= f.number_field :guests %>
    </div>
    <div class="field">
      <%= f.label :event_date %>
      <%= f.date_select :event_date %>
    </div>
    <div class="field">
      <%= f.label :end %>
      <%= f.date_select :end %>
    </div>
    <div class="field">
      <%= f.select :time_of_day, options_for_select(["Morning Hours", "Afternoon Hours", "Evening Hours"], :selected) %>
      <%= f.label :time_of_day %>
    </div>
    <%= f.hidden_field :facility_id, value: @facility.id %>
    <div class="field">
      <%= f.select :layout, options_for_select(@facility.facility_layouts.split(" "), :selected) %>
      <%= f.label :layout %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <%= f.text_area :notes, placeholder: "Enter any special conditions" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/facilities/show.html.erb
<section class="section-sm section-sm-mod-2">
  <div class="container">
    <h2><%= @facility.name %>, <%= link_to @facility.hotel.name, hotel_path(@facility.hotel) %>, <%= @facility.hotel.city %></h2>
    <% if @facility.hotel == current_hotel %>
      <%= link_to "Edit Listing", edit_facility_path %>
    <% end %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8">
        <% if @facility.photos.any? %>
          <div data-lightbox="gallery" class="product-carousel">
            <!-- Slick Carousel-->
            <div class="carousel-slider slider">
              <% @facility.photos.each do |photo| %>
                <div class="item"><a href="images/catalog_single-1_original.jpg" data-lightbox="image">
                  <div class="center-cropped">
                    <%= image_tag photo.image.url, size: "370x250" %></a>
                  </div>
                </div>
              <% end %>


            </div>
            <div class="carousel-thumbnail slider">
              <% @facility.photos.each do |photo| %>
                <div class="item"><%= image_tag photo.image.url, class: "thumb-image" %></div>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= link_to "add facility photos", new_photo_path(@facility) %>
        <div class="row">
          <div class="col-xs-12">
            <h4>Description</h4>
            <p><%= @facility.description %></p>
            <div class="table-responsive">
              <table class="table">
                <colgroup>
                  <col class="col-xs-3">
                  <col class="col-xs-3">
                </colgroup>
                <thead>
                <tr class="bg-gray">
                  <th colspan="2">Conference Facility Info</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>Hotel</td>
                  <td><%= @facility.hotel.name %></td>
                </tr>
                <tr>
                  <td>Location</td>
                  <td><%= @facility.hotel.city %></td>
                </tr>
                <tr>
                  <td>Internet</td>
                  <td><%= @facility.internet %></td>
                </tr>
                <tr>
                  <td>Parking</td>
                    <% if @facility.parking == true %>
                      <td>Available</td>
                    <% else %>
                      <td>Not Available</td>
                    <% end %>
                </tr>
                <tr>
                  <td>Accomodation Available</td>
                    <% if @facility.accomodation == true %>
                      <td><%= @facility.hotel.hotel_manager_first_name %> <%= @facility.hotel.hotel_manager_phone %> </td>
                    <% else %>
                      <td>Not Available</td>
                    <% end %>
                </tr>
                <tr>
                  <td>Swimming Pool</td>
                  <% if @facility.swimming_pool == true %>
                    <td>Available</td>
                  <% else %>
                    <td>Not Available</td>
                  <% end %>
                </tr>
                <tr>
                  <td>Public Adress System</td>
                  <% if @facility.pa_system == true %>
                    <td>Available</td>
                  <% else %>
                    <td>Not Available</td>
                  <% end %>
                </tr>
                <tr>
                  <td>Bar</td>
                  <% if @facility.bar == true %>
                    <td>Available</td>
                  <% else %>
                    <td>Not Available</td>
                  <% end %>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="table-responsive">
              <table class="table">
                <colgroup>
                  <col class="col-xs-4">
                  <col class="col-xs-2">
                  <col class="col-xs-2">
                </colgroup>
                <thead>
                <tr class="bg-gray">
                  <th colspan="3">Conference Facility Capacity</th>
                </tr>
                </thead>
                <tbody>
                  <% i = 0 %>
                    <% @facility.facility_layouts.split(" ").length.times do |orientation| %>
                        <tr>
                          <td><%= @facility.facility_layouts.split(" ")[i] %>
                          <td>Max Capacity: <%= @facility.capacity.split(" ")[i] %></td></td>
                        </tr>
                      <% i += 1 %>
                    <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="catalog-sidebar range">
          <div class="sidebar-module cell-sm-6 cell-md-12 cell-md-push-2">
            <% i = 0 %>
              <% @facility.facility_layouts.split(" ").length.times do |orientation| %>
                <div class="col-md-6" style="font-size: 15px;">
                  <span class="icon icon-sm icon-darker hotel-icon-10"></span><%= @facility.facility_layouts.split(" ")[i] %> - <%= @facility.capacity.split(" ")[i] %>
                </div>
                <% i += 1 %>
              <% end %>
          </div>
          <div class="sidebar-module cell-sm-6 cell-md-12 cell-md-push-3">
            <div class="price">
              <p class="small">Price</p>
              <p><span class="h4"><%= number_to_currency(@facility.price - (@facility.price * 0.09) , :unit => "kes") %>/day</span><span class="h6 text-darker">
                    <del><%= number_to_currency(@facility.price , :unit => "kes") %>/day</del>
                </span>
                </p>
              <div class="btn-group-isotope"><%= link_to "Book Facility", new_booking_path, class: "btn btn-primary btn-primary-transparent btn-md btn-min-width-lg" %></div>
            </div>
          </div>

          <div class="sidebar-module cell-sm-6 cell-md-12 cell-md-push-4">
            <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@facility.hotel.latitude}%2C#{@facility.hotel.longitude}" %>

            <h3>Nearby locations</h3>
            <ul>
            <% for hotel in @facility.hotel.nearbys(10) %>
              <li><%= link_to hotel.name, hotel %> (<%= hotel.distance.round(2) %> miles)</li>
            <% end %>
            </ul>
          </div>

          <div class="sidebar-module cell-sm-6 cell-md-12 cell-md-push-7">
            <h4>Facility Owner</h4>
            <div class="media media-mod-3">
              <div class="media-left round img-width-auto">
              </div>
              <div class="media-body">
                <h6 class="text-primary"><%= @facility.hotel.name %></h6>
                <p class="small text-darker"><%= @facility.hotel.name %></p><a href="callto:#" class="text-bold"><%= @facility.hotel.phone %></a>
              </div>
            </div>
            <%= link_to "View Profile", hotel_path(@facility.hotel), class: "btn btn-primary btn-primary-transparent btn-sm" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>