config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :homes
  get 'home/index'

  root 'home#index'
=======
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :hotels, :controllers => { registrations: 'registrations' }
  devise_for :installs
  resources :facilities do
    resources :bookings
  end
  resources :photos

  devise_scope :hotel do
    get "show/:id" => "registrations#show", as: :hotel
  end

  get "category", to: "facilities#category"

  post "filter", to: "facilities#filter"

  get "results", to: "facilities#results"

  get "booking/:id" => "facilities#new_booking", as: :new_booking

  get "user_bookings" => "bookings#user_bookings", as: :user_bookings

  get "reserve/:id" => "bookings#reserve", as: :reserve

  root 'facilities#index'

  get 'static/index'

  get 'static/categories'

  get 'static/facility_category_list'

  get 'static/single_facility'

  get 'static/add_facility'

  get 'static/login_page'

  get 'static/register_page'

  get 'static/profile'

  get 'static/contact_us'


>>>>>>> 579008f5a1fa7d91706bb5a73fe21633a4510a94
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :facility
  belongs_to :user
end

app/models/facility.rb
class Facility < ApplicationRecord
	belongs_to :hotel
	has_many :photos
	has_many :bookings
	

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	mount_uploader :logo, ImageUploader
	has_many :facilities
	has_many :photos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	geocoded_by :name
	after_validation :geocode, :if => :name_changed?			 
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :hotel
  belongs_to :facility
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :note)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  def new
    @photo = Photo.new
  end

  def create
    @facility = Facility.find(photo_params[:facility_id])
    photo_params[:image].length.times do |i|
      @photo = Photo.new(image: photo_params[:image][i], facility_id: photo_params[:facility_id], hotel_id: photo_params[:hotel_id] )
      if @photo.save != true then redirect_to @facility end
    end
    respond_to do |format|
      format.html { redirect_to @facility, notice: "Photos successfully uploaded" }
    end
  end

  private

  def set_photo
    @photo = Photo,find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:hotel_id, :facility_id, :image => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <title>RailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
=======
    <title>Meet in Africa</title>
    <%= csrf_meta_tags %>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload', :recursive => true %>
    <%= stylesheet_link_tag    'static', media: 'all', 'data-turbolinks-track': 'reload', :recursive => true %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload', :recursive => true %>


    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,700%7CMontserrat:400,700">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', :recursive => true  %>
    <%= javascript_include_tag 'cable', 'data-turbolinks-track': 'reload', :recursive => true  %>
    <%= javascript_include_tag 'html5shiv.min', 'data-turbolinks-track': 'reload', :recursive => true  %>
    <%= javascript_include_tag 'pointer-events.min', 'data-turbolinks-track': 'reload', :recursive => true  %>


    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/">
      <%= image_tag "warning_bar_0000_us.jpg", size: "42x820", alt: "Please Update your browser"%></a></div>
    <![endif]-->

  <div class="rd-navbar-wrap header_corporate">
      <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fullwidth" data-md-layout="rd-navbar-fullwidth" data-lg-layout="rd-navbar-fullwidth" data-device-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fullwidth" data-stick-up-offset="100px">
        <div class="rd-navbar-inner inner-wrap">
          <div class="rd-navbar-panel">
            <!-- RD Navbar Toggle-->
            <button data-rd-navbar-toggle=".rd-navbar-nav-wrap" class="rd-navbar-toggle"><span></span></button>
            <!-- RD Navbar Brand-->
            <div class="rd-navbar-brand"><a href="/" class="brand-name"><%= image_tag "meet-in-africa-logo.png" %></a></div>
          </div>
          <div class="btn-group">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_hotel_session_path, :method => :delete, class: "btn btn-sm btn-primary" %>
              <% if current_user.bookings.any? %>
                <%= link_to "You have #{current_user.bookings.count} bookings", user_bookings_path, class: "btn btn-sm btn-primary" %>
              <% end %>
            <% else %>
            <% if hotel_signed_in? == false %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-sm btn-primary" %>
              <%= link_to "Your Hotel", new_hotel_session_path, class: "btn btn-sm btn-primary" %>
            <% end %>
            <% end %>
            <% if hotel_signed_in? %>
              <%= link_to "Add Facility", new_facility_path, class: "btn btn-sm btn-primary" %>
              <%= link_to "My Hotel", hotel_path(current_hotel), class: "btn btn-sm btn-primary" %>
              <%= link_to "Log Out", destroy_hotel_session_path, :method => :delete, class: "btn btn-sm btn-primary" %>
            <% end %>
          </div>

        </div>
      </nav>
    </div>
  <body>
    <%= yield %>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
    <% end %>
    <%= javascript_include_tag 'script', 'data-turbolinks-track': 'reload', :recursive => true  %>
    <%= javascript_include_tag 'core.min', 'data-turbolinks-track': 'reload', :recursive => true  %>
  </body>
  <footer class="page-foot text-center text-md-left bg-gray">
    <div class="container-fluid">
      <div class="footer-wrap">
        <div class="rd-navbar-brand"><a href="/" class="brand-name">Meet in<br><span>Africa</span></a></div>
        <ul class="list-inline">
          <li><a href="#" class="fa-facebook"></a></li>
          <li><a href="#" class="fa-twitter"></a></li>
          <li><a href="#" class="fa-pinterest-p"></a></li>
          <li><a href="#" class="fa-vimeo"></a></li>
          <li><a href="#" class="fa-google"></a></li>
          <li><a href="#" class="fa-rss"></a></li>
        </ul>
        <div class="copyright">
          <p>&#169;<span id="copyright-year"></span> All Rights Reserved <a href="terms.html">Terms of Use and Privacy Policy</a>
          </p>
        </div>
      </div>
    </div>
  </footer>

>>>>>>> 579008f5a1fa7d91706bb5a73fe21633a4510a94
</html>